### ISSUE TITLE
Write manual test cases for "GelderlandPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#102]
Please write a manual test case for the following pages manual test which involves breaking down the webpage's functionality into specific steps that can be tested.

GelderlandPage: https://prayersconnect.com/mosques/search/Harderwijk%252C%2520Gelderland%252C%2520Netherlands/52.3422025%2C5.6367423/52.3422025%2C5.6367423

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1v4pXXdrtDnI1bMoTChw2GMhktxPvWBu5ayLzeNaXiFk/edit?usp=sharing

**Comment by shejutiqa** [comment]
done

**Comment by LeonSubhan** [comment]
Thank you
