### ISSUE TITLE
Write manual test cases for "NorthBrabantPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#104]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

NorthBrabantPage:
https://prayersconnect.com/mosques/search/%2526%252339%253Bs-Hertogenbosch%252C%2520North%2520Brabant%252C%2520Netherlands/51.6978162%2C5.3036748/51.6978162%2C5.3036748

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
completed 
https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit#gid=1796956612

**Comment by LeonSubhan** [comment]
Thank you.
