### ISSUE TITLE
Write manual test cases for "LimburgPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#108]
Please write a manual test case for the following pages, which involves breaking down the webpage's functionality into specific steps that can be tested.

LimburgPage:
https://prayersconnect.com/mosques/search/Venlo%252C%2520Limburg%252C%2520Netherlands/51.3703748%2C6.172403099999999/51.3703748%2C6.172403099999999

Please use this Google sheet for your test cases.

https://docs.google.com/spreadsheets/d/1RegwjFoV5raCE2WmWKo10hwgGfQZbeixYBSov-HIX0Y/edit?usp=sharing

**Comment by Mohaimin-Rahat** [comment]
Completed

**Comment by LeonSubhan** [comment]
Thank you
