### ISSUE TITLE
Write manual test cases for "FrieslandPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#109]
Please write a manual test case for the following pages, which involves breaking down the webpage's functionality into specific steps that can be tested.

FrieslandPage:
https://prayersconnect.com/mosques/search/Wolvega%252C%2520Friesland%252C%2520Netherlands/52.87655179999999%2C5.9958692/52.87655179999999%2C5.9958692

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
completed and submitted 
https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit#gid=774665431

**Comment by LeonSubhan** [comment]
Thank you.
