### ISSUE TITLE
Write manual test cases for "DrenthePage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#111]
Please write a manual test case for the following pages manual test which involves breaking down the webpage's functionality into specific steps that can be tested.

DrenthePage: https://prayersconnect.com/mosques/search/Hoogeveen%252C%2520Drenthe%252C%2520Netherlands/52.7286158%2C6.490100200000001/52.7286158%2C6.490100200000001

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1v4pXXdrtDnI1bMoTChw2GMhktxPvWBu5ayLzeNaXiFk/edit?usp=sharing

**Comment by shejutiqa** [comment]
done

**Comment by LeonSubhan** [comment]
Thank you
