### ISSUE TITLE
Write manual test cases for "Emilia-RomagnaPAGE"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#112]
Please write a manual test case for the following pages manual test which involves breaking down the webpage's functionality into specific steps that can be tested.

Emilia-RomagnaPAGE:
https://prayersconnect.com/mosques/search/Lugo%252C%2520Emilia-Romagna%252C%2520Italy/44.48072699999999%2C11.8963211/44.48072699999999%2C11.8963211

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1nCvZGxeOC0CEUgaNQv-kppkraK-EDgZKbEx7dDQ4H2o/edit?usp=sharing

**Comment by Smrity44** [comment]
Done

**Comment by LeonSubhan** [comment]
Thank you
