### ISSUE TITLE
Write manual test cases for "TuscanyPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#113]
Please write a manual test case for the following pages manual test which involves breaking down the webpage's functionality into specific steps that can be tested.

TuscanyPage:
https://prayersconnect.com/mosques/search/Montevarchi%252C%2520Tuscany%252C%2520Italy/43.530781%2C11.5639528/43.530781%2C11.5639528

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/16uv2lrNY3rP8KESh2YoVNqxvhFQP9z68COPzNEOMoLM/edit?usp=sharing

**Comment by Mohaimin-Rahat** [comment]
Done

**Comment by LeonSubhan** [comment]
Thank you
