### ISSUE TITLE
Write manual test cases for "LatiumPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#114]
Please write a manual test case for the following pages manual test which involves breaking down the webpage's functionality into specific steps that can be tested.

LatiumPage:
https://prayersconnect.com/mosques/search/Rome%252C%2520Latium%252C%2520Italy/41.9027835%2C12.4963655/41.9027835%2C12.4963655

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/16mkrQRKKItU2IPNJDxnTzdobZewGN5Wu_SMwWPpzf-o/edit?usp=sharing

**Comment by Mohaimin-Rahat** [comment]
Completed

**Comment by LeonSubhan** [comment]
Thank you
