### ISSUE TITLE
Write manual test cases for "MarchesPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#116]
Please write a manual test case for the following pages manual test which involves breaking down the webpage's functionality into specific steps that can be tested.

MarchesPage: https://prayersconnect.com/mosques/search/Senigallia%252C%2520Marches%252C%2520Italy/43.7197926%2C13.2152224/43.7197926%2C13.2152224

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1v4pXXdrtDnI1bMoTChw2GMhktxPvWBu5ayLzeNaXiFk/edit?usp=sharing

**Comment by shejutiqa** [comment]
done

**Comment by LeonSubhan** [comment]
Thank you.
