### ISSUE TITLE
Write manual test cases for "Friuli-Venezia GiuliaPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#118]
Please write a manual test case for the following pages, which involves breaking down the webpage's functionality into specific steps that can be tested.

Friuli-Venezia GiuliaPage:
https://prayersconnect.com/mosques/search/Spilimbergo%252C%2520Friuli-Venezia%2520Giulia%252C%2520Italy/46.1172789%2C12.8992964/46.1172789%2C12.8992964

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
completed and submitted

**Comment by LeonSubhan** [comment]
Thank you.
