### ISSUE TITLE
Write manual test cases for "LiguriaPage", "LombardyPage", and "Trentino-Alto AdigePage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#121]
Please write a manual test case for the following pages, which involves breaking down the webpage's functionality into specific steps that can be tested.

LiguriaPage;
https://prayersconnect.com/mosques/search/Genoa%252C%2520Liguria%252C%2520Italy/44.4056499%2C8.946256/44.4056499%2C8.946256

LombardyPage;
https://prayersconnect.com/mosques/search/Voghera%252C%2520Lombardy%252C%2520Italy/44.99165989999999%2C9.0120442/44.99165989999999%2C9.0120442

Trentino-Alto AdigePage;
https://prayersconnect.com/mosques/search/Bolzano%252C%2520Trentino-Alto%2520Adige%252C%2520Italy/46.4982953%2C11.3547582/46.4982953%2C11.3547582

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
done

**Comment by LeonSubhan** [comment]
Thank you
