### ISSUE TITLE
Write manual test cases for "SouthernDenmarkRegionPage", "ZealandPage", "CentralDenmarkRegionPage" and "LeinsterPage".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#124]
Please write a manual test case for the following pages manual test which involves breaking down the webpage's functionality into specific steps that can be tested.

SouthernDenmarkRegionPage:
https://prayersconnect.com/mosques/search/Odense%252C%2520Southern%2520Denmark%2520Region%252C%2520Denmark/55.40375599999999%2C10.40237/55.40375599999999%2C10.40237

ZealandPage:
https://prayersconnect.com/mosques/search/Nyk%25C3%25B8bing%2520Falster%252C%2520Zealand%252C%2520Denmark/54.76542200000001%2C11.875492/54.76542200000001%2C11.875492

CentralDenmarkRegionPage;
https://prayersconnect.com/mosques/search/Aarhus%252C%2520Central%2520Denmark%2520Region%252C%2520Denmark/56.162939%2C10.203921/56.162939%2C10.203921

LeinsterPage:
https://prayersconnect.com/mosques/search/Carlow%252C%2520Leinster%252C%2520Ireland/52.8365072%2C-6.9341359/52.8365072%2C-6.9341359

Test Cases:

SouthernDenmarkRegionPage:
https://docs.google.com/spreadsheets/d/1rR0EtkAQ8dlwOEHMOIIFLlYAt822GDpUPMMg343eV4E/edit?usp=sharing

ZealandPage:
https://docs.google.com/spreadsheets/d/10G9HHIbWsecpg-NMZVOVawOYrVvqqDNpYDzWXTIop9E/edit?usp=sharing

CentralDenmarkRegionPage:
https://docs.google.com/spreadsheets/d/1sE8g4tZUZS8mHNr5LVxV2XGRb-nmt-InBvKcAlzwF8k/edit?usp=sharing

LeinsterPage:
https://docs.google.com/spreadsheets/d/1pB6GBP3ZnvtIjOM5qD9Yi5Pvadpg_vWj0OoH09fBtkA/edit?usp=sharing

**Comment by Mohaimin-Rahat** [comment]
Completed

**Comment by LeonSubhan** [comment]
Thank you.
