### ISSUE TITLE
Write a manual test case fo "https://prayersconnect.com/"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#17]
Please write a manual test case for "https://prayersconnect.com/" which involves breaking down the functionality of the webpage into specific steps that can be tested.

Please use this Google sheet for your test cases.
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by shimul5888** [comment]
Bhaia assalamu alaikum. I have completed my task. Regards.

https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Thank you.
