### ISSUE TITLE
Write manual test case on multiple pages.

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#23]
Please write a manual test case for "https://prayersconnect.com/regions/provinces?id=46&cid=1" and "https://prayersconnect.com/regions/provinces?id=50&cid=1"  which involves breaking down the functionality of the webpage into specific steps that can be tested.

https://prayersconnect.com/regions/provinces?id=50&cid=1
https://prayersconnect.com/regions/provinces?id=46&cid=1

Please use this Google sheet for your test cases.

https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit?usp=sharing

**Comment by AyshaShetu** [comment]
Test cases for Germany is done. I got a server error on a province. Created a ticket for that and labeled as a bug. Please check.
Germany page-https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=870616686
Netherlands page-
https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=2020125766

**Comment by LeonSubhan** [comment]
Okay, thank you for the update.

**Comment by LeonSubhan** [comment]
Hello Apu, is this done?

**Comment by AyshaShetu** [comment]
Yes bhaiya!  Both of them are done. I started a new one already. You can assign the next two. I am hoping to finish them by sunday night.

**Comment by LeonSubhan** [comment]
Thank you.
