### ISSUE TITLE
Write manual test case for the "Donate" frame

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#26]
Please write a manual test case for the "Donate" frame which involves breaking down the functionality of the webpage into specific steps that can be tested.

![iScreen Shoter - Google Chrome - 230928091102](https://github.com/prayersconnect/qa/assets/108196213/b26c6458-f4e7-4fed-8ce4-82d90a9c54c1)

Please use this Google sheet for your test cases.
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by shimul5888** [comment]
Bhaia assalamu alaikum. I have completed my task and submitted accordingly. Best Regards.

https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Thank you.
