### ISSUE TITLE
Write manual test cases for "https://prayersconnect.com/regions/provinces?id=3&cid=1" and "https://prayersconnect.com/regions/provinces?id=47&cid=1".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#27]
Please write a manual test case for "https://prayersconnect.com/regions/provinces?id=3&cid=1" and "https://prayersconnect.com/regions/provinces?id=47&cid=1" which involves breaking down the functionality of the webpage into specific steps that can be tested.

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
### Manual test case for Denmark link provided below:
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing
### Test Data Link provided below:
https://prayersconnect.com/regions/provinces?id=3&cid=1
@LeonSubhan

**Comment by Fairuznewaz** [comment]
### Manual test case for Ireland link provided below: 
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

### Test Data link provided below: 
https://prayersconnect.com/regions/provinces?id=47&cid=1

@LeonSubhan

**Comment by LeonSubhan** [comment]
Thank you.
