### ISSUE TITLE
Write manual test cases for "https://prayersconnect.com/regions/provinces?id=30&cid=1" and "https://prayersconnect.com/regions/provinces?id=6&cid=1"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#28]
Please write a manual test case for "SpainPage: https://prayersconnect.com/regions/provinces?id=30&cid=1" and "SwitzerlandPage: https://prayersconnect.com/regions/provinces?id=6&cid=1" which involves breaking down the functionality of the webpage into specific steps that can be tested.

Please use this Google sheet for your test cases.
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by shimul5888** [comment]
Task of Spain Page Completed and submitted accordingly
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit#gid=743559893
Task of Switzerland page completed and submitted accordingly
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit#gid=782905692

**Comment by LeonSubhan** [comment]
Thank you
