### ISSUE TITLE
Write manual test cases for "AustraliaPage: https://prayersconnect.com/regions/provinces?id=43&cid=3" and "NewZealandPage: https://prayersconnect.com/regions/provinces?id=51&cid=3".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#29]
Please write a manual test case for "AustraliaPage: https://prayersconnect.com/regions/provinces?id=43&cid=3" and "NewZealandPage: https://prayersconnect.com/regions/provinces?id=51&cid=3" which involves breaking down the functionality of the webpage into specific steps that can be tested.

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
completed
https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit#gid=1628079725

**Comment by LeonSubhan** [comment]
Thank you.
