### ISSUE TITLE
Write manual test cases for "WashingtonPage: https://prayersconnect.com/mosques/search/Seattle%252C%2520Washington%252C%2520United%2520States/47.6062095%2C-122.3320708/47.6062095%2C-122.3320708".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#30]
Please write a manual test case for "WashingtonPage: https://prayersconnect.com/mosques/search/Seattle%252C%2520Washington%252C%2520United%2520States/47.6062095%2C-122.3320708/47.6062095%2C-122.3320708" which involves breaking down the functionality of the webpage into specific steps that can be tested.

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
done

**Comment by LeonSubhan** [comment]
Thank you.
