### ISSUE TITLE
Write manual test cases for "NewYorkPage: https://prayersconnect.com/mosques/search/Queens%252C%2520New%2520York%252C%2520United%2520States/40.7282239%2C-73.7948516/40.7282239%2C-73.7948516".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#31]
Please write a manual test case for "NewYorkPage: https://prayersconnect.com/mosques/search/Queens%252C%2520New%2520York%252C%2520United%2520States/40.7282239%2C-73.7948516/40.7282239%2C-73.7948516" which involves breaking down the functionality of the webpage into specific steps that can be tested.

Please use this Google sheet for your test cases.
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Please hold on to this issue, work on issue #34

**Comment by shimul5888** [comment]
Submitted herewith:
https://docs.google.com/spreadsheets/d/1VG999MAq6GLH0lbUGhgr7P7oVcW5jUbI4AyEhYjf62U/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Thank you.
