### ISSUE TITLE
Write manual test cases for "SingaporePage: https://prayersconnect.com/regions/provinces?id=209&cid=3", and "FijiPage: https://prayersconnect.com/regions/provinces?id=15&cid=3".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#32]
Please write a manual test case for "SingaporePage: https://prayersconnect.com/regions/provinces?id=209&cid=3", and "FijiPage: https://prayersconnect.com/regions/provinces?id=15&cid=3" which involves breaking down the functionality of the webpage into specific steps that can be tested.

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
### Manual test case link for Asia & Pacific:
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

### Manual test case link for Singapore:
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

### Manual test case link for Fiji:
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

### Manual test case link for Bangladesh:
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

@LeonSubhan

**Comment by LeonSubhan** [comment]
Thank you
