### ISSUE TITLE
Write manual test xases for YukonPage, NorthwestTarritoriesPage, PrinceEdwardIslandPage, NewfoundlandAndLabradorPage, NewBrunswickPage, NovaScotiaPage.

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#33]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

NovaScotiaPage: https://prayersconnect.com/mosques/search/Halifax%252C%2520Nova%2520Scotia%252C%2520Canada/44.6505571%2C-63.5977882/44.6505571%2C-63.5977882

NewBrunswickPage: https://prayersconnect.com/mosques/search/Moncton%252C%2520New%2520Brunswick%252C%2520Canada/46.0878165%2C-64.7782313/46.0878165%2C-64.7782313

NewfoundlandAndLabradorPage: https://prayersconnect.com/mosques/search/St.%2520John%2526%252339%253Bs%252C%2520Newfoundland%2520and%2520Labrador%252C%2520Canada/47.6071205%2C-52.6894688/47.6071205%2C-52.6894688

PrinceEdwardIslandPage: https://prayersconnect.com/mosques/search/Charlottetown%252C%2520Prince%2520Edward%2520Island%252C%2520Canada/46.23824%2C-63.13107040000001/46.23824%2C-63.13107040000001

NorthwestTarritoriesPage: https://prayersconnect.com/mosques/search/Inuvik%252C%2520Northwest%2520Territories%252C%2520Canada/68.3684863%2C-133.7370547/68.3684863%2C-133.7370547

YukonPage: https://prayersconnect.com/mosques/search/Whitehorse%252C%2520Yukon%252C%2520Canada/60.7197137%2C-135.0522761/60.7197137%2C-135.0522761

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
### Nova Scotia
https://docs.google.com/spreadsheets/d/1YP0n9blJra8AWBchRanlsS_x5yLSWs7mTwxlKDZWoOg/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
### Newfoundland & Labrador
https://docs.google.com/spreadsheets/d/1YP0n9blJra8AWBchRanlsS_x5yLSWs7mTwxlKDZWoOg/edit?usp=sharing

Only 4 mosques found nearby.

**Comment by Fairuznewaz** [comment]
### New Brunswick
https://docs.google.com/spreadsheets/d/1YP0n9blJra8AWBchRanlsS_x5yLSWs7mTwxlKDZWoOg/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
### Prince Edward Island

https://docs.google.com/spreadsheets/d/1YP0n9blJra8AWBchRanlsS_x5yLSWs7mTwxlKDZWoOg/edit?usp=sharing

Only 2 mosques found nearby.

**Comment by Fairuznewaz** [comment]
### Northwest Territories

https://docs.google.com/spreadsheets/d/1YP0n9blJra8AWBchRanlsS_x5yLSWs7mTwxlKDZWoOg/edit?usp=sharing

Only 1 mosque found nearby.

**Comment by Fairuznewaz** [comment]
### Yukon

https://docs.google.com/spreadsheets/d/1YP0n9blJra8AWBchRanlsS_x5yLSWs7mTwxlKDZWoOg/edit?usp=sharing

1 mosque found nearby.

**Comment by LeonSubhan** [comment]
Thank you.
