### ISSUE TITLE
Write manual test cases for ManitobaPage.

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#34]
Please write a manual test case for "Manitobapage: https://prayersconnect.com/mosques/search/Winnipeg%252C%2520Manitoba%252C%2520Canada/49.8954221%2C-97.1385145/49.8954221%2C-97.1385145" which involves breaking down the functionality of the webpage into specific steps that can be tested.

Please use this Google sheet for your test cases.
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by shimul5888** [comment]
Completed and submitted herewith:
https://docs.google.com/spreadsheets/d/1VG999MAq6GLH0lbUGhgr7P7oVcW5jUbI4AyEhYjf62U/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Thank you.
