### ISSUE TITLE
Write manual test cases for NewHampshirePage, AlaskaPage, MontanaPage, SouthDakotaPage, WyomingPage, VermontPage.

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#35]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

NewHampshirePage: https://prayersconnect.com/mosques/search/Lebanon%252C%2520New%2520Hampshire%252C%2520United%2520States/43.6422934%2C-72.2517569/43.6422934%2C-72.2517569

AlaskaPage: https://prayersconnect.com/mosques/search/Anchorage%252C%2520Alaska%252C%2520United%2520States/61.2180556%2C-149.9002778/61.2180556%2C-149.9002778

MontanaPage: https://prayersconnect.com/mosques/search/Missoula%252C%2520Montana%252C%2520United%2520States/46.8721284%2C-113.9940314/46.8721284%2C-113.9940314

SouthDakotaPage: https://prayersconnect.com/mosques/search/Sioux%2520Falls%252C%2520South%2520Dakota%252C%2520United%2520States/43.5473028%2C-96.728333/43.5473028%2C-96.728333

WyomingPage: https://prayersconnect.com/mosques/search/Cheyenne%252C%2520Wyoming%252C%2520United%2520States/41.1399814%2C-104.8202462/41.1399814%2C-104.8202462

VermontPage: https://prayersconnect.com/mosques/search/Colchester%252C%2520Vermont%252C%2520United%2520States/44.5439375%2C-73.1479068/44.5439375%2C-73.1479068

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
done

**Comment by LeonSubhan** [comment]
Thank you.
