### ISSUE TITLE
Write manual test cases for HawaiiPage, RhodeIslandPage, IdahoPage, MainePage, NorthDakotaPage, and WestVirginiaPage.

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#36]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

HawaiiPage https://prayersconnect.com/mosques/search/Honolulu%252C%2520Hawaii%252C%2520United%2520States/21.3098845%2C-157.8581401/21.3098845%2C-157.8581401

RhodeIslandPage: https://prayersconnect.com/mosques/search/Pawtucket%252C%2520Rhode%2520Island%252C%2520United%2520States/41.878711%2C-71.38255579999999/41.878711%2C-71.38255579999999

IdahoPage: https://prayersconnect.com/mosques/search/Twin%2520Falls%252C%2520Idaho%252C%2520United%2520States/42.5558381%2C-114.4700518/42.5558381%2C-114.4700518

MainePage: https://prayersconnect.com/mosques/search/Portland%252C%2520Maine%252C%2520United%2520States/43.6590993%2C-70.2568189/43.6590993%2C-70.2568189

NorthDakotaPage: https://prayersconnect.com/mosques/search/Grand%2520Forks%252C%2520North%2520Dakota%252C%2520United%2520States/47.9252568%2C-97.0328547/47.9252568%2C-97.0328547

WestVirginiaPage: https://prayersconnect.com/mosques/search/Princeton%252C%2520West%2520Virginia%252C%2520United%2520States/37.3662293%2C-81.1025918/37.3662293%2C-81.1025918

Please use this Google sheet for your test cases.

https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit?usp=sharing

**Comment by AyshaShetu** [comment]
All done.

HawaiiPage: https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=2098987959

RhodeIslandPage: https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=1075374584

IdahoPage: https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=846422148

MainePage: https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=1279173446

NorthDakotaPage: https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=811218296

WestVirginiaPage: https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=1877409329

**Comment by LeonSubhan** [comment]
Thank you.
