### ISSUE TITLE
Write manual test cases for "CaliforniaPage".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#39]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

CaliforniaPage: https://prayersconnect.com/mosques/search/Anaheim%252C%2520California%252C%2520United%2520States/33.8365932%2C-117.9143012/33.8365932%2C-117.9143012

Please use this Google sheet for your test cases.

https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit?usp=sharing

**Comment by AyshaShetu** [comment]
ticket #39 Done. https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=836302319

**Comment by LeonSubhan** [comment]
Thank you.
