### ISSUE TITLE
Write manual test cases for "TexasPage".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#40]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

TexasPage: https://prayersconnect.com/mosques/search/Irving%252C%2520Texas%252C%2520United%2520States/32.8140177%2C-96.9488945/32.8140177%2C-96.9488945

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
@LeonSubhan completed ticket #40

**Comment by LeonSubhan** [comment]
Thank you.
