### ISSUE TITLE
Write manual test xases for "FloridaPage".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#41]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

FloridaPage: https://prayersconnect.com/mosques/search/Boca%2520Raton%252C%2520Florida%252C%2520United%2520States/26.3683064%2C-80.1289321/26.3683064%2C-80.1289321

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
Florida Page Test case link:
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Thank you.
