### ISSUE TITLE
Write manual test cases for "IllinoisPage".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#42]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

IllinoisPage: https://prayersconnect.com/mosques/search/Chicago%252C%2520Illinois%252C%2520United%2520States/41.8781136%2C-87.6297982/41.8781136%2C-87.6297982

Please use this Google sheet for your test cases.
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by shimul5888** [comment]
Task completed and submitted accordingly
https://docs.google.com/spreadsheets/d/1VG999MAq6GLH0lbUGhgr7P7oVcW5jUbI4AyEhYjf62U/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Thank you.

**Comment by LeonSubhan** [comment]
Thank you.

**Comment by LeonSubhan** [comment]
Thank you.
