### ISSUE TITLE
Write manual test cases for "PennsylvaniaPage". 

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#44]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

PennsylvaniaPage: https://prayersconnect.com/mosques/search/Pittsburgh%252C%2520Pennsylvania%252C%2520United%2520States/40.44062479999999%2C-79.9958864/40.44062479999999%2C-79.9958864

Please use this Google sheet for your test cases.
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by shimul5888** [comment]
Task is completed
https://docs.google.com/spreadsheets/d/1VG999MAq6GLH0lbUGhgr7P7oVcW5jUbI4AyEhYjf62U/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Thank you.

**Comment by LeonSubhan** [comment]
Thank you.
