### ISSUE TITLE
Write manual test xases for "MichiganPage".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#45]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

MichiganPage: https://prayersconnect.com/mosques/search/Queens%252C%2520New%2520York%252C%2520United%2520States/40.7282239%2C-73.7948516/40.7282239%2C-73.7948516

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit#gid=125654671

**Comment by LeonSubhan** [comment]
Thank you.
