### ISSUE TITLE
Write manual test cases for "OhioPage".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#46]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

OhioPage: https://prayersconnect.com/mosques/search/Toledo%252C%2520Ohio%252C%2520United%2520States/41.6528052%2C-83.5378674/41.6528052%2C-83.5378674

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
completed

**Comment by LeonSubhan** [comment]
Thank you
