### ISSUE TITLE
Write manual test cases for "VirginiaPage".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#47]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

VirginiaPage: https://prayersconnect.com/mosques/search/Roanoke%252C%2520Virginia%252C%2520United%2520States/37.2709704%2C-79.9414266/37.2709704%2C-79.9414266

Please use this Google sheet for your test cases.

https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit?usp=sharing

**Comment by AyshaShetu** [comment]
here is the completed task: https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=184476946. 
Duplicate mosques also listed on the given link https://docs.google.com/spreadsheets/d/17fe4lKbZ5DVA0Oxhdo8rlN7ozSfjCQMbbrPawA5h8bo/edit#gid=0

**Comment by LeonSubhan** [comment]
Thank you.
