### ISSUE TITLE
Write manual test cases for "GeorgiaPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#48]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

GeorgiaPage: https://prayersconnect.com/mosques/search/Lawrenceville%252C%2520Georgia%252C%2520United%2520States/33.9562149%2C-83.9879625/33.9562149%2C-83.9879625

Please use this Google sheet for your test cases.
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by shimul5888** [comment]
Task completed
https://docs.google.com/spreadsheets/d/1VG999MAq6GLH0lbUGhgr7P7oVcW5jUbI4AyEhYjf62U/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Thank you.
