### ISSUE TITLE
Write manual test xases for "NorthCarolinaPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#49]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

NorthCarolinaPage: https://prayersconnect.com/mosques/search/Smithfield%252C%2520North%2520Carolina%252C%2520United%2520States/35.4786152%2C-78.375024/35.4786152%2C-78.375024

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit#gid=1982729820

**Comment by LeonSubhan** [comment]
Thank you.

**Comment by LeonSubhan** [comment]
Thank you.
