### ISSUE TITLE
Write manual test xases for "MinnesotaPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#50]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

MinnesotaPage: https://prayersconnect.com/mosques/search/Saint%2520Paul%252C%2520Minnesota%252C%2520United%2520States/44.9537029%2C-93.0899578/44.9537029%2C-93.0899578

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit#gid=11891480

**Comment by LeonSubhan** [comment]
Thank you.
