### ISSUE TITLE
Write manual test cases for "MarylandPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#51]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

MarylandPage: https://prayersconnect.com/mosques/search/Lanham%252C%2520Maryland%252C%2520United%2520States/38.96851119999999%2C-76.8620327/38.96851119999999%2C-76.8620327

MassachusettsPage: https://prayersconnect.com/mosques/search/Boston%252C%2520Massachusetts%252C%2520United%2520States/42.3600825%2C-71.0588801/42.3600825%2C-71.0588801

ConnecticutPage:
https://prayersconnect.com/mosques/search/Mansfield%252C%2520Connecticut%252C%2520United%2520States/41.788489%2C-72.2292913/41.788489%2C-72.2292913

Please use this Google sheet for your test cases.
https://docs.google.com/spreadsheets/d/1ci-_ZZpDDkxCGeviDORBB0CPspBzZBmmSnvbjvDf9KE/edit?usp=sharing

**Comment by shimul5888** [comment]
Mary Land page completed
https://docs.google.com/spreadsheets/d/1VG999MAq6GLH0lbUGhgr7P7oVcW5jUbI4AyEhYjf62U/edit?usp=sharing

**Comment by LeonSubhan** [comment]
Thank you.
