### ISSUE TITLE
Write manual test cases for "TennesseePage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#52]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

TennesseePage: https://prayersconnect.com/mosques/search/Franklin%252C%2520Tennessee%252C%2520United%2520States/35.9250637%2C-86.8688899/35.9250637%2C-86.8688899

MissousiPage:
https://prayersconnect.com/mosques/search/St.%2520Louis%252C%2520Missouri%252C%2520United%2520States/38.6270025%2C-90.19940419999999/38.6270025%2C-90.19940419999999

Please use this Google sheet for your test cases.

https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit?usp=sharing

**Comment by AyshaShetu** [comment]
Tennessee Page : https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=373148658
 Missouri page : https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=878645925

**Comment by LeonSubhan** [comment]
Thank you.
