### ISSUE TITLE
Write manual test cases for "IndianaPage".

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#58]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

IndianaPage: https://prayersconnect.com/mosques/search/Fort%2520Wayne%252C%2520Indiana%252C%2520United%2520States/41.079273%2C-85.1393513/41.079273%2C-85.1393513

Please use this Google sheet for your test cases.

https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit?usp=sharing

**Comment by AyshaShetu** [comment]
Indiana page : https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=615772101

**Comment by LeonSubhan** [comment]
Thank you
