### ISSUE TITLE
Write manual test xases for "WisconsinPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#60]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

WisconsinPage: https://prayersconnect.com/mosques/search/Oostburg%252C%2520Wisconsin%252C%2520United%2520States/43.62277479999999%2C-87.7945323/43.62277479999999%2C-87.7945323

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit#gid=855557440

**Comment by LeonSubhan** [comment]
Thank you
