### ISSUE TITLE
Write manual test cases for "QuebecPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#71]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

QuebecPage: https://prayersconnect.com/mosques/search/Montr%25C3%25A9al%252C%2520Quebec%252C%2520Canada/45.45621%2C-73.546783/45.45621%2C-73.546783

Please use this Google sheet for your test cases.

https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit?usp=sharing

**Comment by AyshaShetu** [comment]
Quebec Page:
https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=522322061
all the problematic mosque id number is enlisted with problem and remark in the image review sheet.

**Comment by LeonSubhan** [comment]
Thank you
