### ISSUE TITLE
Write manual test cases for "AlbertaPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#72]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

AlbertaPage: https://prayersconnect.com/mosques/search/Calgary%252C%2520Alberta%252C%2520Canada/51.0861712%2C-113.9989784/51.0861712%2C-113.9989784

Please use this Google Sheet for your test cases

https://docs.google.com/spreadsheets/d/1TPTDXvuPvRhw-U4YBsxJ58iATH1P4MCsE98E3ydKECQ/edit?usp=sharing

**Comment by taneeza** [comment]
done
