### ISSUE TITLE
Write manual test cases for "BritishColumbiaPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#73]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

BritishColumbiaPage: https://prayersconnect.com/mosques/search/New%2520Westminster%252C%2520British%2520Columbia%252C%2520Canada/49.2030398%2C-122.9072654/49.2030398%2C-122.9072654

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit#gid=1101415571

**Comment by LeonSubhan** [comment]
Thank you.
