### ISSUE TITLE
Write manual test cases for "ScotlandPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#75]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

ScotlandPage: https://prayersconnect.com/mosques/search/Livingston%252C%2520Scotland%252C%2520United%2520Kingdom/55.90079%2C-3.50038/55.90079%2C-3.50038

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit#gid=216035700

**Comment by LeonSubhan** [comment]
Thank you
