### ISSUE TITLE
Write manual test cases for "NorthernIrelandPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#77]
Please write a manual test case for the following pages, which involves breaking down the functionality of the webpage into specific steps that can be tested.

NorthernIrelandPage: https://prayersconnect.com/mosques/search/Belfast%252C%2520Northern%2520Ireland%252C%2520United%2520Kingdom/54.58422%2C-5.93091/54.58422%2C-5.93091

Please use this Google sheet for your test cases.

https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit?usp=sharing

**Comment by AyshaShetu** [comment]
https://docs.google.com/spreadsheets/d/1PIzULJpRSBqpsujibqaAh4GZrrIZb48yqy2q3yJpSBI/edit#gid=496516621

**Comment by LeonSubhan** [comment]
Thank you
