### ISSUE TITLE
Write manual test cases for "OccitaniaPage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#80]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

OccitaniaPage: https://prayersconnect.com/mosques/search/Pamiers%252C%2520Occitanie%252C%2520France/43.114753%2C1.607953/43.114753%2C1.607953

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit?usp=sharing

**Comment by Fairuznewaz** [comment]
https://docs.google.com/spreadsheets/d/1O1NJRmobfNfk6cGgc5BWHCMhRSjF6vJK3C-AljYxgHo/edit#gid=62910257

Most of the pages have mosque with mixed locations which include Spain.

**Comment by LeonSubhan** [comment]
Thank you
