### ISSUE TITLE
Write manual test cases for "ProvenceAlpesCotedAzurPage

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#82]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

ProvenceAlpesCotedAzurPage: 
https://prayersconnect.com/mosques/search/Avignon%252C%2520Provence-Alpes-Cote%2520d%2526%252339%253BAzur%252C%2520France/43.95355%2C4.80647/43.95355%2C4.80647

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1nCvZGxeOC0CEUgaNQv-kppkraK-EDgZKbEx7dDQ4H2o/edit?usp=sharing

**Comment by Smrity44** [comment]
https://docs.google.com/spreadsheets/d/1nCvZGxeOC0CEUgaNQv-kppkraK-EDgZKbEx7dDQ4H2o/edit#gid=0

**Comment by LeonSubhan** [comment]
Thank you
