### ISSUE TITLE
Write manual test cases for "HautsdeFrancePage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#83]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

HautsdeFrancePage: 
https://prayersconnect.com/mosques/search/Roubaix%252C%2520Hauts-de-France%252C%2520France/50.68661%2C3.15876/50.68661%2C3.15876

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1A3wT6bmPhbFsdjhuCpzBCPo3y7x1pKMtgTrbZDDKis4/edit?usp=sharing

**Comment by Mohaimin-Rahat** [comment]
Manual test cases for "HautsdeFrancePage" Completed

**Comment by LeonSubhan** [comment]
Thank you.
