### ISSUE TITLE
Write manual test cases for "BourgogneFrancheComtePage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#86]
Please write a manual test case for the following pages manual test which involves breaking down the webpage's functionality into specific steps that can be tested.

BourgogneFrancheComtePage:
https://prayersconnect.com/mosques/search/Grandvillars%252C%2520Bourgogne-Franche-Comte%252C%2520France/47.538646%2C6.972968/47.538646%2C6.972968

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1nCvZGxeOC0CEUgaNQv-kppkraK-EDgZKbEx7dDQ4H2o/edit?usp=sharing

**Comment by Smrity44** [comment]
https://docs.google.com/spreadsheets/d/1nCvZGxeOC0CEUgaNQv-kppkraK-EDgZKbEx7dDQ4H2o/edit#gid=1022412187
