### ISSUE TITLE
Write manual test cases for "Rhineland-PalatinatePage"

### ISSUE THREAD

**Issue by LeonSubhan** [prayersconnect/qa#96]
Please write a manual test case for the following pages manual test which involves breaking down the functionality of the webpage into specific steps that can be tested.

Rhineland-PalatinatePage:
https://prayersconnect.com/mosques/search/Ludwigshafen%252C%2520Rhineland-Palatinate%252C%2520Germany/49.4774018%2C8.4447451/49.4774018%2C8.4447451

Please use this Google doc for your test cases.

https://docs.google.com/spreadsheets/d/1v4pXXdrtDnI1bMoTChw2GMhktxPvWBu5ayLzeNaXiFk/edit?usp=sharing

**Comment by shejutiqa** [comment]
done

**Comment by LeonSubhan** [comment]
Thank you
